<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
       <ProjectReference Include="..\MSFS2024AddonManger.core\MSFS2024AddonManager.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Linking\" />
    <Folder Include="Settings\" />
    <Folder Include="Scanning\" />
    <Folder Include="Profiles\" />
  </ItemGroup>

</Project>
