<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>Assets\AppIcon.ico</ApplicationIcon>
    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <InformationalVersion>1.0.0</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <Authors>Andrew Brown</Authors>
    <Company>Andrew Brown</Company>
    <Product>MSFS 2024 Addons Manager</Product>
    <Description>Manage MSFS 2024 addon libraries, profiles, and Community folders.</Description>
    <Copyright>Andrew Brown © 2026</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FontAwesome.Sharp.Pro" Version="6.6.0" />
    <PackageReference Include="Krypton.Toolkit" Version="105.26.7.201" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Assets\" />
    <Folder Include="Helpers\" />
    <Folder Include="Themes\" />
    <Folder Include="Resources\" />
    <Folder Include="UI\Icons\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MSFS2024AddonManger.core\MSFS2024AddonManager.Core.csproj" />
    <ProjectReference Include="..\MSFS2024AddonManger.Services\MSFS2024AddonManager.Services.csproj" />
  </ItemGroup>

</Project>
